
# Will cause syntax errors since they begin with numbers
variables_to_rename:
  1stFlrSF: FirstFlrSF
  2ndFlrSF: SecondFlrSF
  3SsnPorch: ThreeSsnPortch

HouseDataInputSchema:
  Alley: Optional[str]
  BedroomAbvGr: Optional[int]
  BldgType: Optional[str]
  BsmtCond: Optional[str]
  BsmtExposure: Optional[str]
  BsmtFinSF1: Optional[float]
  BsmtFinSF2: Optional[float]
  BsmtFinType1: Optional[str]
  BsmtFinType2: Optional[str]
  BsmtFullBath: Optional[float]
  BsmtHalfBath: Optional[float]
  BsmtQual: Optional[str]
  BsmtUnfSF: Optional[float]
  CentralAir: Optional[str]
  Condition1: Optional[str]
  Condition2: Optional[str]
  Electrical: Optional[str]
  EnclosedPorch: Optional[int]
  ExterCond: Optional[str]
  ExterQual: Optional[str]
  Exterior1st: Optional[str]
  Exterior2nd: Optional[str]
  Fence: Optional[str]
  FireplaceQu: Optional[str]
  Fireplaces: Optional[int]
  Foundation: Optional[str]
  FullBath: Optional[int]
  Functional: Optional[str]
  GarageArea: Optional[float]
  GarageCars: Optional[float]
  GarageCond: Optional[str]
  GarageFinish: Optional[str]
  GarageQual: Optional[str]
  GarageType: Optional[str]
  GarageYrBlt: Optional[float]
  GrLivArea: Optional[int]
  HalfBath: Optional[int]
  Heating: Optional[str]
  HeatingQC: Optional[str]
  HouseStyle: Optional[str]
  Id: Optional[int]
  KitchenAbvGr: Optional[int]
  KitchenQual: Optional[str]
  LandContour: Optional[str]
  LandSlope: Optional[str]
  LotArea: Optional[int]
  LotConfig: Optional[str]
  LotFrontage: Optional[float]
  LotShape: Optional[str]
  LowQualFinSF: Optional[int]
  MSSubClass: Optional[int]
  MSZoning: Optional[str]
  MasVnrArea: Optional[float]
  MasVnrType: Optional[str]
  MiscFeature: Optional[str]
  MiscVal: Optional[int]
  MoSold: Optional[int]
  Neighborhood: Optional[str]
  OpenPorchSF: Optional[int]
  OverallCond: Optional[int]
  OverallQual: Optional[int]
  PavedDrive: Optional[str]
  PoolArea: Optional[int]
  PoolQC: Optional[str]
  RoofMatl: Optional[str]
  RoofStyle: Optional[str]
  SaleCondition: Optional[str]
  SaleType: Optional[str]
  ScreenPorch: Optional[int]
  Street: Optional[str]
  TotRmsAbvGrd: Optional[int]
  TotalBsmtSF: Optional[float]
  Utilities: Optional[str]
  WoodDeckSF: Optional[int]
  YearBuilt: Optional[int]
  YearRemodAdd: Optional[int]
  YrSold: Optional[int]
  FirstFlrSF: Optional[int]  # renamed
  SecondFlrSF: Optional[int]  # renamed
  ThreeSsnPortch: Optional[int]  # renamed


features:
  - MSSubClass
  - MSZoning
  - LotFrontage
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - OverallQual
  - OverallCond
  - YearRemodAdd
  - RoofStyle
  - Exterior1st
  - ExterQual
  - Foundation
  - BsmtQual
  - BsmtExposure
  - BsmtFinType1
  - HeatingQC
  - CentralAir
  - FirstFlrSF  # renamed
  - SecondFlrSF  # renamed
  - GrLivArea
  - BsmtFullBath
  - HalfBath
  - KitchenQual
  - TotRmsAbvGrd
  - Functional
  - Fireplaces
  - FireplaceQu
  - GarageFinish
  - GarageCars
  - GarageArea
  - PavedDrive
  - WoodDeckSF
  - ScreenPorch
  - SaleCondition
  # this one is only to calculate temporal variable:
  - YrSold

alpha: 0.001

# to set the random seed
random_state: 0

# categorical variables with NA in train set
categorical_vars_with_na_frequent:
  - BsmtQual
  - BsmtExposure
  - BsmtFinType1
  - GarageFinish

categorical_vars_with_na_missing:
  - FireplaceQu

numerical_vars_with_na:
  - LotFrontage

temporal_vars:
  - YearRemodAdd

ref_var: YrSold


# variables to log transform
numericals_log_vars:
  - LotFrontage
  - FirstFlrSF
  - GrLivArea

binarize_vars:
  - ScreenPorch

# variables to map
qual_vars:
  - ExterQual
  - BsmtQual
  - HeatingQC
  - KitchenQual
  - FireplaceQu

exposure_vars:
  - BsmtExposure

finish_vars:
  - BsmtFinType1

garage_vars:
  - GarageFinish

categorical_vars:
  - MSSubClass
  - MSZoning
  - LotShape
  - LandContour
  - LotConfig
  - Neighborhood
  - RoofStyle
  - Exterior1st
  - Foundation
  - CentralAir
  - Functional
  - PavedDrive
  - SaleCondition

# variable mappings
qual_mappings:
  Po: 1
  Fa: 2
  TA: 3
  Gd: 4
  Ex: 5
  Missing: 0
  NA: 0

exposure_mappings:
  'No': 1
  Mn: 2
  Av: 3
  Gd: 4


finish_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  LwQ: 2
  Rec: 3
  BLQ: 4
  ALQ: 5
  GLQ: 6


garage_mappings:
  Missing: 0
  NA: 0
  Unf: 1
  RFn: 2
  Fin: 3